-- MySQL Script generated by MySQL Workbench
-- Mon Jun 20 19:20:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteque` DEFAULT CHARACTER SET utf8 ;
USE `biblioteque` ;

-- -----------------------------------------------------
-- Table `auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteque`.`auteur` (
  `idAuteur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `nationnalite` VARCHAR(45) NULL,
  `dateNaissance` DATE NULL,
  PRIMARY KEY (`idAuteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteque`.`categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `nomCategorie` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteque`.`livre` (
  `idLivre` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(100) NOT NULL,
  `langueLivre` VARCHAR(45) NULL,
  `livrecol` VARCHAR(45) NULL,
  `anneeSortie` DATE NULL,
  `nbPages` INT NULL,
  `anneeParution` DATE NULL,
  `image` VARCHAR(200) NULL,
  `auteur_idAuteur` INT NOT NULL,
  `categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`idLivre`),
  INDEX `fk_livre_auteur_idx` (`auteur_idAuteur` ASC) ,
  INDEX `fk_livre_categorie1_idx` (`categorie_idCategorie` ASC),
  CONSTRAINT `fk_livre_auteur`
    FOREIGN KEY (`auteur_idAuteur`)
    REFERENCES `biblioteque`.`auteur` (`idAuteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_categorie1`
    FOREIGN KEY (`categorie_idCategorie`)
    REFERENCES `biblioteque`.`categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `emprunter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteque`.`emprunter` (
  `etudiant_idEtudiant` INT NOT NULL,
  `livre_idLivre` INT NOT NULL,
  `dateDebut` VARCHAR(45) NOT NULL,
  `dateFin` VARCHAR(45) NOT NULL,
  `status` BLOB NOT NULL,
  PRIMARY KEY (`etudiant_idEtudiant`, `livre_idLivre`),
  INDEX `fk_etudiant_has_livre_livre1_idx` (`livre_idLivre` ASC) ,
  INDEX `fk_etudiant_has_livre_etudiant1_idx` (`etudiant_idEtudiant` ASC) ,
  CONSTRAINT `fk_etudiant_has_livre_etudiant1`
    FOREIGN KEY (`etudiant_idEtudiant`)
    REFERENCES `biblioteque`.`etudiant` (`idEtudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiant_has_livre_livre1`
    FOREIGN KEY (`livre_idLivre`)
    REFERENCES `biblioteque`.`livre` (`idLivre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteque`.`etudiant` (
  `idEtudiant` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  PRIMARY KEY (`idEtudiant`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
